---
apiVersion: v2
name: owncloud
version: 0.0.0-devel
description: ownCloud Server Helm chart
# renovate: datasource=docker depName=owncloud/server
appVersion: 10.14.0
home: https://owncloud.com/
keywords:
  - owncloud
  - files
  - collaboration
  - sharing
maintainers:
  - name: ownCloud GmbH
    email: devops@owncloud.com
    url: https://owncloud.com
type: application
# Keep 'kubeVersion' in sync with 'kubernetesVersions' in .drone.star
kubeVersion: "~1.27.0-0 || ~1.28.0-0 || ~1.29.0-0 || ~1.30.0-0 || ~1.31.0-0"
sources:
  - https://github.com/owncloud-docker/helm-charts
  - https://github.com/owncloud-docker/server
  - https://github.com/owncloud/core
