apiVersion: v2
name: owncloud
description: ownCloud 10 Helm chart
keywords:
  - owncloud
maintainers:
  - name: ownCloud GmbH
    email: devops@owncloud.com
    url: https://owncloud.com
type: application
version: 0.1.0
appVersion: 10.11.0
kubeVersion: "~1.20.0 || ~1.21.0 || ~1.22.0 || ~1.23.0 || ~1.24.0 || ~1.25.0" # if this changes, also kubernetesVersions in .drone.star needs to be changed
sources:
  - https://github.com/owncloud-docker/helm
  - https://github.com/owncloud-docker/server
  - https://github.com/owncloud/core
