apiVersion: v1
kind: ConfigMap
metadata:
  name: owncloud-env-config
  labels:
    {{- include "owncloud.labels" . | nindent 4 }}
data:
  OWNCLOUD_ACCESSLOG_LOCATION: {{ .Values.owncloud.accesslogLocation | quote }}
  OWNCLOUD_ACCOUNTS_ENABLE_MEDIAL_SEARCH: {{ .Values.owncloud.accountsEnableMedialSearch | quote }}
  OWNCLOUD_ADMIN_PASSWORD: {{ .Values.owncloud.adminPassword | quote }}
  OWNCLOUD_ADMIN_USERNAME: {{ .Values.owncloud.adminUsername | quote }}
  OWNCLOUD_ALLOW_USER_TO_CHANGE_DISPLAY_NAME: {{ .Values.owncloud.allowUserToChangeDisplayName | quote }}
  OWNCLOUD_APPS_DEPRECATED: {{ .Values.owncloud.apps.deprecated | quote }}
  OWNCLOUD_APPS_DISABLE: {{ .Values.owncloud.apps.disable | quote }}
  OWNCLOUD_APPS_ENABLE: {{ .Values.owncloud.apps.enable | quote }}
  OWNCLOUD_APPS_INSTALL: {{ .Values.owncloud.apps.install | quote }}
  OWNCLOUD_APPS_INSTALL_MAJOR: {{ .Values.owncloud.apps.installMajor | quote }}
  OWNCLOUD_APPS_UNINSTALL: {{ .Values.owncloud.apps.uninstall | quote }}
  OWNCLOUD_BACKGROUND_MODE: {{ .Values.owncloud.backgroundMode | quote }}
  OWNCLOUD_BLACKLISTED_FILES: {{ .Values.owncloud.blacklistedFiles | quote }}
  OWNCLOUD_CACHE_CHUNK_GC_TTL: {{ .Values.owncloud.cacheChunkGcTtl | quote }}
  OWNCLOUD_CACHE_PATH: {{ .Values.owncloud.cachePath | quote }}
  OWNCLOUD_CHECK_FOR_WORKING_WELLKNOWN_SETUP: {{ .Values.owncloud.checkForWorkingWellknownSetup | quote }}
  OWNCLOUD_CIPHER: {{ .Values.owncloud.cipher | quote }}
  OWNCLOUD_COMMENTS_MANAGER_FACTORY: {{ .Values.owncloud.commentsManagerFactory | quote }}
  OWNCLOUD_CORS_ALLOWED_DOMAINS: {{ .Values.owncloud.corsAllowedDomains | quote }}
  OWNCLOUD_CROND_ENABLED: "false" # Disable ownCloud container's cronJob in Kubernetes in favor of Kubernetes' own CronJob
  OWNCLOUD_CSRF_DISABLED: {{ .Values.owncloud.csrfDisabled | quote }}
  OWNCLOUD_DAV_CHUNK_BASE_DIR: {{ .Values.owncloud.davChunkBaseDir | quote }}
  OWNCLOUD_DAV_ENABLE_ASYNC: {{ .Values.owncloud.davEnableAsync | quote }}
  OWNCLOUD_DB_FAIL: {{ .Values.owncloud.db.fail | quote }}
  OWNCLOUD_DB_HOST: {{ .Values.owncloud.db.host | quote }}
  OWNCLOUD_DB_NAME: {{ .Values.owncloud.db.name | quote }}
  OWNCLOUD_DB_PASSWORD: {{ .Values.owncloud.db.password | quote }}
  OWNCLOUD_DB_PREFIX: {{ .Values.owncloud.db.prefix | quote }}
  OWNCLOUD_DB_TIMEOUT: {{ .Values.owncloud.db.timeout | quote }}
  OWNCLOUD_DB_TYPE: {{ .Values.owncloud.db.type | quote }}
  OWNCLOUD_DB_USERNAME: {{ .Values.owncloud.db.username | quote }}
  OWNCLOUD_DEBUG: {{ .Values.owncloud.debug | quote }}
  OWNCLOUD_DEFAULT_APP: {{ .Values.owncloud.defaultApp | quote }}
  OWNCLOUD_DEFAULT_LANGUAGE: {{ .Values.owncloud.defaultLanguage | quote }}
  OWNCLOUD_DOMAIN: {{ .Values.owncloud.domain | quote }}
  OWNCLOUD_TRUSTED_DOMAINS: {{ include "owncloud.trustedDomains" . }}
  OWNCLOUD_ENABLED_PREVIEW_PROVIDERS: {{ .Values.owncloud.enabledPreviewProviders | quote }}
  OWNCLOUD_ENABLE_AVATARS: {{ .Values.owncloud.enableAvatars | quote }}
  OWNCLOUD_ENABLE_CERTIFICATE_MANAGEMENT: {{ .Values.owncloud.enableCertificateManagement | quote }}
  OWNCLOUD_ENABLE_PREVIEWS: {{ .Values.owncloud.enablePreviews | quote }}
  OWNCLOUD_ENABLE_OIDC_REWRITE_URL: {{ .Values.owncloud.enableOidcRewriteUrl | quote }}
  OWNCLOUD_ENTRYPOINT_INITIALIZED: {{ .Values.owncloud.entrypointInitialized | quote }}
  OWNCLOUD_ERRORLOG_LOCATION: {{ .Values.owncloud.errorlogLocation | quote }}
  OWNCLOUD_EXCLUDED_DIRECTORIES: {{ .Values.owncloud.excludedDirectories | quote }}
  OWNCLOUD_FILELOCKING_ENABLED: {{ .Values.owncloud.filelockingEnabled | quote }}
  OWNCLOUD_FILELOCKING_TTL: {{ .Values.owncloud.filelockingTtl | quote }}
  OWNCLOUD_FILESYSTEM_CACHE_READONLY: {{ .Values.owncloud.filesystemCacheReadonly | quote }}
  OWNCLOUD_FILESYSTEM_CHECK_CHANGES: {{ .Values.owncloud.filesystemCheckChanges | quote }}
  OWNCLOUD_FILES_EXTERNAL_ALLOW_NEW_LOCAL: {{ .Values.owncloud.filesExternalAllowNewLocal | quote }}
  OWNCLOUD_FORWARDED_FOR_HEADERS: {{ .Values.owncloud.forwardedForHeaders | quote }}
  OWNCLOUD_HASHING_COST: {{ .Values.owncloud.hashingCost | quote }}
  OWNCLOUD_HAS_INTERNET_CONNECTION: {{ .Values.owncloud.hasInternetConnection | quote }}
  OWNCLOUD_HTACCESS_REWRITE_BASE: {{ .Values.owncloud.htaccessRewriteBase | quote }}
  OWNCLOUD_HTTP_COOKIE_SAMESITE: {{ .Values.owncloud.httpCookieSamesite | quote }}
  OWNCLOUD_INTEGRITY_EXCLUDED_FILES: {{ .Values.owncloud.integrityExcludedFiles | quote }}
  OWNCLOUD_INTEGRITY_IGNORE_MISSING_APP_SIGNATURE: {{ .Values.owncloud.integrityIgnoreMissingAppSignature | quote }}
  OWNCLOUD_KNOWLEDGEBASE_ENABLED: {{ .Values.owncloud.knowledgebaseEnabled | quote }}
  OWNCLOUD_APPSTORE_ENABLED: {{ .Values.owncloud.appstoreEnabled | quote }}
  OWNCLOUD_LICENSE_KEY: {{ .Values.owncloud.licenseKey | quote }}
  OWNCLOUD_LICENSE_CLASS: {{ .Values.owncloud.licenseClass | quote }}
  OWNCLOUD_LOGIN_ALTERNATIVES: {{ .Values.owncloud.loginAlternatives | quote }}
  OWNCLOUD_LOG_DATE_FORMAT: {{ .Values.owncloud.log.dateFormat | quote }}
  OWNCLOUD_LOG_FILE: {{ .Values.owncloud.log.file | quote }}
  OWNCLOUD_LOG_LEVEL: {{ .Values.owncloud.log.level | quote }}
  OWNCLOUD_LOG_ROTATE_SIZE: {{ .Values.owncloud.log.rotateSize | quote }}
  OWNCLOUD_LOG_TIMEZONE: {{ .Values.owncloud.log.timezone | quote }}
  OWNCLOUD_LOST_PASSWORD_LINK: {{ .Values.owncloud.lostPasswordLink | quote }}
  OWNCLOUD_MAIL_DOMAIN: {{ .Values.owncloud.mail.domain | quote }}
  OWNCLOUD_MAIL_FROM_ADDRESS: {{ .Values.owncloud.mail.fromAddress | quote }}
  OWNCLOUD_MAIL_SMTP_AUTH: {{ .Values.owncloud.mail.smtp.auth | quote }}
  OWNCLOUD_MAIL_SMTP_AUTH_TYPE: {{ .Values.owncloud.mail.smtp.authType | quote }}
  OWNCLOUD_MAIL_SMTP_DEBUG: {{ .Values.owncloud.mail.smtp.debug | quote }}
  OWNCLOUD_MAIL_SMTP_HOST: {{ .Values.owncloud.mail.smtp.host | quote }}
  OWNCLOUD_MAIL_SMTP_MODE: {{ .Values.owncloud.mail.smtp.mode | quote }}
  OWNCLOUD_MAIL_SMTP_NAME: {{ .Values.owncloud.mail.smtp.name | quote }}
  OWNCLOUD_MAIL_SMTP_PASSWORD: {{ .Values.owncloud.mail.smtp.password | quote }}
  OWNCLOUD_MAIL_SMTP_PORT: {{ .Values.owncloud.mail.smtp.port | quote }}
  OWNCLOUD_MAIL_SMTP_SECURE: {{ .Values.owncloud.mail.smtp.secure | quote }}
  OWNCLOUD_MAIL_SMTP_TIMEOUT: {{ .Values.owncloud.mail.smtp.timeout | quote }}
  OWNCLOUD_MAINTENANCE: {{ .Values.owncloud.maintenance | quote }}
  OWNCLOUD_MARKETPLACE_CA: {{ .Values.owncloud.marketplace.ca | quote }}
  OWNCLOUD_MARKETPLACE_KEY: {{ .Values.owncloud.marketplace.key | quote }}
  OWNCLOUD_MAX_EXECUTION_TIME: {{ .Values.owncloud.maxExecutionTime | quote }}
  OWNCLOUD_MAX_FILESIZE_ANIMATED_GIFS_PUBLIC_SHARING: {{ .Values.owncloud.maxFilesizeAnimatedGifsPublicSharing | quote }}
  OWNCLOUD_MAX_INPUT_TIME: {{ .Values.owncloud.maxInputTime | quote }}
  OWNCLOUD_MAX_UPLOAD: {{ .Values.owncloud.maxUpload | quote }}
  OWNCLOUD_MEMCACHED_ENABLED: {{ .Values.owncloud.memcachedEnabled | quote }}
  OWNCLOUD_MEMCACHED_HOST: {{ .Values.owncloud.memcachedHost | quote }}
  OWNCLOUD_MEMCACHED_OPTIONS: {{ .Values.owncloud.memcachedOptions | quote }}
  OWNCLOUD_MEMCACHED_PORT: {{ .Values.owncloud.memcachedPort | quote }}
  OWNCLOUD_MEMCACHED_STARTUP_TIMEOUT: {{ .Values.owncloud.memcachedStartupTimeout | quote }}
  OWNCLOUD_MEMCACHE_LOCAL: {{ .Values.owncloud.memcacheLocal | quote }}
  OWNCLOUD_MEMCACHE_LOCKING: {{ .Values.owncloud.memcacheLocking | quote }}
  OWNCLOUD_MINIMUM_SUPPORTED_DESKTOP_VERSION: {{ .Values.owncloud.minimumSupportedDesktopVersion | quote }}
  OWNCLOUD_MOUNT_FILE: {{ .Values.owncloud.mountFile | quote }}
  OWNCLOUD_MYSQL_UTF8MB4: {{ .Values.owncloud.mysqlUtf8Mb4 | quote }}
  {{- if .Values.owncloud.objectstore.enabled }}
  OWNCLOUD_OBJECTSTORE_BUCKET: {{ .Values.owncloud.objectstore.bucket | quote }}
  OWNCLOUD_OBJECTSTORE_CLASS: {{ .Values.owncloud.objectstore.class | quote }}
  OWNCLOUD_OBJECTSTORE_ENABLED: {{ .Values.owncloud.objectstore.enabled | quote }}
  OWNCLOUD_OBJECTSTORE_ENDPOINT: {{ .Values.owncloud.objectstore.endpoint | quote }}
  OWNCLOUD_OBJECTSTORE_KEY: {{ .Values.owncloud.objectstore.key | quote }}
  OWNCLOUD_OBJECTSTORE_PATHSTYLE: {{ .Values.owncloud.objectstore.pathstyle | quote }}
  OWNCLOUD_OBJECTSTORE_REGION: {{ .Values.owncloud.objectstore.region | quote }}
  OWNCLOUD_OBJECTSTORE_SECRET: {{ .Values.owncloud.objectstore.secret | quote }}
  OWNCLOUD_OBJECTSTORE_VERSION: {{ .Values.owncloud.objectstore.version | quote }}
  {{- end }}
  OWNCLOUD_OPERATION_MODE: {{ .Values.owncloud.operationMode | quote }}
  OWNCLOUD_OVERWRITE_CLI_URL: {{ .Values.owncloud.overwriteCliUrl | quote }}
  OWNCLOUD_OVERWRITE_COND_ADDR: {{ .Values.owncloud.overwriteCondAddr | quote }}
  OWNCLOUD_OVERWRITE_HOST: {{ .Values.owncloud.overwriteHost | quote }}
  OWNCLOUD_OVERWRITE_PROTOCOL: {{ .Values.owncloud.overwriteProtocol | quote }}
  OWNCLOUD_OVERWRITE_WEBROOT: {{ .Values.owncloud.overwriteWebroot | quote }}
  OWNCLOUD_PART_FILE_IN_STORAGE: {{ .Values.owncloud.partFileInStorage | quote }}
  OWNCLOUD_POST_CRONJOB_PATH: {{ .Values.owncloud.postCronjobPath | quote }}
  OWNCLOUD_POST_INSTALL_PATH: {{ .Values.owncloud.postInstallPath | quote }}
  OWNCLOUD_POST_SERVER_PATH: {{ .Values.owncloud.postServerPath | quote }}
  OWNCLOUD_PREVIEW_LIBREOFFICE_PATH: {{ .Values.owncloud.preview.libreofficePath | quote }}
  OWNCLOUD_PREVIEW_MAX_FILESIZE_IMAGE: {{ .Values.owncloud.preview.maxFilesizeImage | quote }}
  OWNCLOUD_PREVIEW_MAX_SCALE_FACTOR: {{ .Values.owncloud.preview.maxScaleFactor | quote }}
  OWNCLOUD_PREVIEW_MAX_X: {{ .Values.owncloud.preview.maxX | quote }}
  OWNCLOUD_PREVIEW_MAX_Y: {{ .Values.owncloud.preview.maxY | quote }}
  OWNCLOUD_PREVIEW_OFFICE_CL_PARAMETERS: {{ .Values.owncloud.preview.officeClParameters | quote }}
  OWNCLOUD_PRE_CRONJOB_PATH: {{ .Values.owncloud.preCronjobPath | quote }}
  OWNCLOUD_PRE_INSTALL_PATH: {{ .Values.owncloud.preInstallPath | quote }}
  OWNCLOUD_PRE_SERVER_PATH: {{ .Values.owncloud.preServerPath | quote }}
  OWNCLOUD_PROTOCOL: {{ .Values.owncloud.protocol | quote }}
  OWNCLOUD_PROXY: {{ .Values.owncloud.proxy | quote }}
  OWNCLOUD_PROXY_USERPWD: {{ .Values.owncloud.proxyUserpwd | quote }}
  OWNCLOUD_QUOTA_INCLUDE_EXTERNAL_STORAGE: {{ .Values.owncloud.quotaIncludeExternalStorage | quote }}
  {{- if .Values.owncloud.redis.enabled }}
  OWNCLOUD_REDIS_DB: {{ .Values.owncloud.redis.db | quote }}
  OWNCLOUD_REDIS_ENABLED: "true"
  OWNCLOUD_REDIS_FAILOVER_MODE: {{ .Values.owncloud.redis.failoverMode | quote }}
  OWNCLOUD_REDIS_HOST: {{ .Values.owncloud.redis.host | quote }}
  OWNCLOUD_REDIS_PASSWORD: {{ .Values.owncloud.redis.password | quote }}
  {{- end }}
  OWNCLOUD_REDIS_PORT: {{ .Values.owncloud.redis.port | quote }}
  OWNCLOUD_REDIS_READ_TIMEOUT: {{ .Values.owncloud.redis.readTimeout | quote }}
  OWNCLOUD_REDIS_SEEDS: {{ .Values.owncloud.redis.seeds | quote }}
  OWNCLOUD_REDIS_SESSION_LOCKING_ENABLED: {{ .Values.owncloud.redis.sessionLockingEnabled | quote }}
  OWNCLOUD_REDIS_SESSION_LOCK_RETRIES: {{ .Values.owncloud.redis.sessionLockRetries | quote }}
  OWNCLOUD_REDIS_SESSION_LOCK_WAIT_TIME: {{ .Values.owncloud.redis.sessionLockWaitTime | quote }}
  OWNCLOUD_REDIS_STARTUP_TIMEOUT: {{ .Values.owncloud.redis.startupTimeout | quote }}
  OWNCLOUD_REDIS_TIMEOUT: {{ .Values.owncloud.redis.timeout | quote }}
  OWNCLOUD_REMEMBER_LOGIN_COOKIE_LIFETIME: {{ .Values.owncloud.rememberLoginCookieLifetime | quote }}
  OWNCLOUD_SECRET: {{ .Values.owncloud.secret | quote }}
  OWNCLOUD_SESSION_KEEPALIVE: {{ .Values.owncloud.session.keepalive | quote }}
  OWNCLOUD_SESSION_LIFETIME: {{ .Values.owncloud.session.lifetime | quote }}
  OWNCLOUD_SESSION_FORCED_LOGOUT_TIMEOUT: {{ .Values.owncloud.session.forcedLogoutTimeout | quote }}
  OWNCLOUD_SESSION_SAVE_HANDLER: {{ .Values.owncloud.session.saveHandler | quote }}
  OWNCLOUD_SESSION_SAVE_PATH: {{ .Values.owncloud.session.savePath | quote }}
  OWNCLOUD_SHARE_FOLDER: {{ .Values.owncloud.shareFolder | quote }}
  OWNCLOUD_SHARING_FEDERATION_ALLOW_HTTP_FALLBACK: {{ .Values.owncloud.sharingFederationAllowHttpFallback | quote }}
  OWNCLOUD_SHARING_MANAGER_FACTORY: {{ .Values.owncloud.sharingManagerFactory | quote }}
  OWNCLOUD_SHOW_SERVER_HOSTNAME: {{ .Values.owncloud.showServerHostname | quote }}
  OWNCLOUD_SINGLEUSER: {{ .Values.owncloud.singleuser | quote }}
  OWNCLOUD_SKELETON_DIRECTORY: {{ .Values.owncloud.skeletonDirectory | quote }}
  OWNCLOUD_SKIP_CHMOD: {{ .Values.owncloud.skipChmod | quote }}
  OWNCLOUD_SKIP_CHOWN: "true"
  OWNCLOUD_SMB_LOGGING_ENABLE: {{ .Values.owncloud.smbLoggingEnable | quote }}
  OWNCLOUD_SQLITE_JOURNAL_MODE: {{ .Values.owncloud.sqliteJournalMode | quote }}
  OWNCLOUD_SUB_URL: {{ .Values.owncloud.subUrl | quote }}
  OWNCLOUD_SYSTEMTAGS_MANAGER_FACTORY: {{ .Values.owncloud.systemtagsManagerFactory | quote }}
  OWNCLOUD_TEMP_DIRECTORY: {{ .Values.owncloud.tempDirectory | quote }}
  OWNCLOUD_TOKEN_AUTH_ENFORCED: {{ .Values.owncloud.tokenAuthEnforced | quote }}
  OWNCLOUD_TRASHBIN_PURGE_LIMIT: {{ .Values.owncloud.trashbin.purgeLimit | quote }}
  OWNCLOUD_TRASHBIN_RETENTION_OBLIGATION: {{ .Values.owncloud.trashbin.retentionObligation | quote }}
  OWNCLOUD_TRUSTED_PROXIES: {{ .Values.owncloud.trustedProxies | quote }}
  OWNCLOUD_UPDATER_SERVER_URL: {{ .Values.owncloud.updaterServerUrl | quote }}
  OWNCLOUD_UPDATE_CHECKER: {{ .Values.owncloud.updateChecker | quote }}
  OWNCLOUD_UPGRADE_AUTOMATIC_APP_UPDATES: {{ .Values.owncloud.upgradeAutomaticAppUpdates | quote }}
  OWNCLOUD_USER_SEARCH_MIN_LENGTH: {{ .Values.owncloud.userSearchMinLength | quote }}
  OWNCLOUD_VERSIONS_RETENTION_OBLIGATION: {{ .Values.owncloud.versionsRetentionObligation | quote }}
  OWNCLOUD_VERSION_HIDE: {{ .Values.owncloud.versionHide | quote }}
  OWNCLOUD_VOLUME_APPS: {{ .Values.owncloud.volume.apps | quote }}
  OWNCLOUD_VOLUME_CONFIG: {{ .Values.owncloud.volume.config | quote }}
  OWNCLOUD_VOLUME_FILES: {{ .Values.owncloud.volume.files | quote }}
  OWNCLOUD_VOLUME_ROOT: {{ .Values.owncloud.volume.root | quote }}
  OWNCLOUD_VOLUME_SESSIONS: {{ .Values.owncloud.volume.sessions | quote }}
